### ISSUE TITLE
GitHub Action Automation for Issues

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#797]
Currently, issues added to the Taqueria project are not automatically added to the working projects. This results in additional maintenance and issues falling through the cracks

There is a GH action we can use [here](https://github.com/actions/add-to-project)

```
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: OR
```

## AC:
- [x] Any issues opened in the Taqueria repo with the label `dev` should be added to the `Taqueria Dev` project with status: `Eng Backlog`
- [x] All other issues should be added to the `Inbox and Triage` project with status: `Inbox`
- [ ] When PR's are marked ready for review, they should be added to the `Taqueria Dev` project with status: `In Review`
